apiVersion: v1
kind: Service
metadata:
  name: compliance-service
  namespace: staging
spec:
  type: NodePort
  selector:
    app: compliance-service
  ports:
    - port: 80          # Service port
      targetPort: 3000  # Container port
      nodePort: 32082   # Unique NodePort (range: 30000–32
