apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-service
  namespace: staging
  labels:
    app: identity-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identity-service
  template:
    metadata:
      labels:
        app: identity-service
    spec:
      containers:
        - name: identity-service
          image: 311141556953.dkr.ecr.ap-southeast-5.amazonaws.com/asb-microservice/identity-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: '50m'
              memory: '64Mi'
            limits:
              cpu: '250m'
              memory: '256Mi'
          envFrom:
            - secretRef:
                name: asb-secrets
