apiVersion: v1
kind: Service
metadata:
  name: identity-service
  namespace: staging
spec:
  type: NodePort
  selector:
    app: identity-service
  ports:
    - port: 80          # ClusterIP service port
      targetPort: 3000  # Container port
      nodePort: 32080   # NodePort (must be in range 30000–32767)
